#######################################################################
#                          MCTennis                                   #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  mctennis:
    aliases:
      - "tennis"
