#######################################################################
#                          MCTennis                                   #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  mctennis:
    aliases:
      - tennis
    usage: "[&9MCTennis&f] Use /mctennis help to see more info about the plugin."
    description: All commands for the MCTennis plugin.
    permission-message: You do not have permission.
