name: MCTennis
version: 1.0.0
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.mctennis.MCTennisPlugin
softdepend: [ PlaceholderAPI ]
api-version: 1.18
commands:
  mctennis:
    usage: Use /mctennis help to see more info about the plugin.
    description: All commands for the MCTennis plugin.
    permission-message: You do not have permission.
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.2.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.2.0
  - com.google.inject:guice:5.0.1
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.3.0
  - com.fasterxml.jackson.core:jackson-databind:2.2.3
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2
  - com.google.code.gson:gson:2.8.6
